[2021-11-03 12:47:50.280] [exthost] [info] extension host started
[2021-11-03 12:47:50.280] [exthost] [info] Skipping acquiring lock for /home/skywalker/.config/Code/User/workspaceStorage/0cb9f0b78f44695a7e3e4d5466b2c2ef.
[2021-11-03 12:47:52.045] [exthost] [info] ExtensionService#_doActivateExtension vscode.microsoft-authentication, startup: false, activationEvent: 'onAuthenticationRequest:microsoft'
[2021-11-03 12:47:52.046] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/microsoft-authentication/dist/extension.js
[2021-11-03 12:47:52.173] [exthost] [info] ExtensionService#_doActivateExtension ms-python.python, startup: false, activationEvent: 'onLanguage:python', root cause: ms-python.vscode-pylance
[2021-11-03 12:47:52.174] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension
[2021-11-03 12:47:52.771] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter, startup: false, activationEvent: 'onLanguage:python'
[2021-11-03 12:47:52.771] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/skywalker/.vscode/extensions/ms-toolsai.jupyter-2021.9.1101343141/out/client/extension
[2021-11-03 12:47:53.653] [exthost] [info] ExtensionService#_doActivateExtension vscode.debug-auto-launch, startup: true, activationEvent: '*'
[2021-11-03 12:47:53.653] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/debug-auto-launch/dist/extension
[2021-11-03 12:47:53.671] [exthost] [info] ExtensionService#_doActivateExtension vscode.git, startup: true, activationEvent: '*', root cause: vscode.github
[2021-11-03 12:47:53.673] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/git/dist/main
[2021-11-03 12:47:55.612] [exthost] [info] ExtensionService#_doActivateExtension vscode.github, startup: true, activationEvent: '*'
[2021-11-03 12:47:55.612] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/github/dist/extension.js
[2021-11-03 12:48:03.232] [exthost] [info] ExtensionService#_doActivateExtension ms-toolsai.jupyter-renderers, startup: false, activationEvent: 'api', root cause: ms-toolsai.jupyter
[2021-11-03 12:48:03.232] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/skywalker/.vscode/extensions/ms-toolsai.jupyter-renderers-1.0.3/out/extension_renderer/index.js
[2021-11-03 12:48:03.261] [exthost] [info] ExtensionService#_doActivateExtension vscode.emmet, startup: false, activationEvent: 'onStartupFinished'
[2021-11-03 12:48:03.261] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/emmet/dist/node/emmetNodeMain
[2021-11-03 12:48:03.343] [exthost] [info] ExtensionService#_doActivateExtension vscode.merge-conflict, startup: false, activationEvent: 'onStartupFinished'
[2021-11-03 12:48:03.344] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/merge-conflict/dist/mergeConflictMain
[2021-11-03 12:48:03.638] [exthost] [info] eager extensions activated
[2021-11-03 12:48:03.807] [exthost] [info] ExtensionService#_doActivateExtension ms-vscode.js-debug, startup: false, activationEvent: 'onCommand:extension.js-debug.clearAutoAttachVariables'
[2021-11-03 12:48:03.807] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/ms-vscode.js-debug/src/extension.js
[2021-11-03 12:48:04.563] [exthost] [info] ExtensionService#_doActivateExtension ms-python.vscode-pylance, startup: false, activationEvent: 'onLanguage:python'
[2021-11-03 12:48:04.564] [exthost] [info] ExtensionService#loadCommonJSModule file:///home/skywalker/.vscode/extensions/ms-python.vscode-pylance-2021.10.3/dist/extension.bundle.js
[2021-11-03 12:48:06.575] [exthost] [info] ExtensionService#_doActivateExtension vscode.github-authentication, startup: false, activationEvent: 'onAuthenticationRequest:github'
[2021-11-03 12:48:06.576] [exthost] [info] ExtensionService#loadCommonJSModule file:///usr/share/code/resources/app/extensions/github-authentication/dist/extension.js
[2021-11-03 12:48:58.130] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:48:58.131] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:48:58.984] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:48:58.985] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:48:59.049] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:48:59.049] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 12:49:00.215] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:49:00.215] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:53:23.997] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:53:23.997] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:53:25.622] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:53:25.623] [exthost] [error] Error: name must not be falsy
	at Function.validate (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:30472)
	at new r (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:30421)
	at new r (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:87:17220)
	at q (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:52:326104)
	at Array.map (<anonymous>)
	at Object.asDocumentSymbols (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:52:331442)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:118287
	at async l.provideDocumentSymbols (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:166891)
[2021-11-03 12:53:30.109] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:53:30.110] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:53:41.394] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:53:41.396] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:53:41.445] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:53:41.447] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:53:45.450] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:53:45.450] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 12:53:45.457] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:53:45.457] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 12:54:42.576] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:42.576] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:112927
	at async U.resolveCompletionItem (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:181423)
[2021-11-03 12:54:42.584] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:42.584] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:112927
	at async U.resolveCompletionItem (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:181423)
[2021-11-03 12:54:43.794] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:43.795] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:54:47.851] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:47.851] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:54:47.865] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:47.866] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:114707
	at async H.provideSignatureHelp (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:184514)
[2021-11-03 12:54:47.868] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:47.869] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:114707
	at async H.provideSignatureHelp (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:184514)
[2021-11-03 12:54:47.893] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:47.893] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:114707
	at async H.provideSignatureHelp (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:184514)
[2021-11-03 12:54:47.907] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:47.907] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:114707
	at async H.provideSignatureHelp (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:184514)
[2021-11-03 12:54:48.227] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:48.227] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:114707
	at async H.provideSignatureHelp (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:184514)
[2021-11-03 12:54:48.613] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:48.613] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:54:48.621] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:54:48.621] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:55:51.528] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:55:51.529] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 12:56:35.997] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:56:35.997] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:56:50.535] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:56:50.536] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:57:51.518] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:57:51.518] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:57:51.521] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:57:51.524] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:114707
	at async H.provideSignatureHelp (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:184514)
[2021-11-03 12:58:31.133] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:58:31.133] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:114707
	at async H.provideSignatureHelp (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:184514)
[2021-11-03 12:58:31.134] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:58:31.135] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:58:49.264] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:58:49.265] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 12:59:34.503] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:59:34.503] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:112531
	at async U.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:180703)
[2021-11-03 12:59:34.507] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:59:34.508] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:112531
	at async U.provideCompletionItems (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:180703)
[2021-11-03 12:59:34.579] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:59:34.593] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:59:34.596] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:59:34.601] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at runNextTicks (internal/process/task_queues.js:58:5)
	at processImmediate (internal/timers.js:434:9)
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 12:59:34.913] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 12:59:34.913] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:112927
	at async U.resolveCompletionItem (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:181423)
[2021-11-03 13:01:05.141] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:01:05.141] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:01:08.307] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:01:08.307] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:01:14.661] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:01:14.662] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:04:04.326] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:04:04.326] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:05:04.810] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:05:04.810] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:05:34.425] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:05:34.426] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:05:49.466] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:05:49.467] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:05:49.484] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:05:49.485] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:06:26.234] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:06:26.234] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:06:27.013] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:06:27.014] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:06:47.373] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:06:47.373] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:06:47.479] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:06:47.480] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:06:47.667] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:06:47.667] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:118365
	at async l.provideDocumentSymbols (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:166891)
[2021-11-03 13:07:03.256] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:07:03.257] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:07:08.551] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:07:08.551] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:07:32.052] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:07:32.052] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:08:08.213] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:08:08.214] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:121238
	at async T.provideCodeActions (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:172403)
[2021-11-03 13:08:32.289] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:08:32.289] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:08:50.955] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:08:50.955] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:10:24.823] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:10:24.824] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:12:33.463] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:12:33.463] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:12:33.671] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:12:33.671] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:16:17.389] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:16:17.389] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:17:13.443] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:17:13.443] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
[2021-11-03 13:17:13.458] [exthost] [error] [ms-python.python] provider FAILED
[2021-11-03 13:17:13.459] [exthost] [error] Canceled: Canceled
	at _.makeCancelError (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153526)
	at _.handleFailedRequest (/home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:153377)
	at /home/skywalker/.vscode/extensions/ms-python.python-2021.10.1365161279/out/client/extension.js:9:113719
	at async s.provideHover (/usr/share/code/resources/app/out/vs/workbench/services/extensions/node/extensionHostProcess.js:94:170095)
